"""Shared programmatic filtering for repository and diff review evidence."""

from __future__ import annotations

from pathlib import PurePosixPath

DEFAULT_REVIEW_IGNORE_DIRS = frozenset(
    {
        ".git",
        ".mypy_cache",
        ".next",
        ".pytest_cache",
        ".ruff_cache",
        ".venv",
        "__pycache__",
        "build",
        "coverage",
        "dist",
        "htmlcov",
        "node_modules",
        "site-packages",
        "target",
        "venv",
        "vendor",
    }
)

DEFAULT_REVIEW_BINARY_EXTS = frozenset(
    {
        ".7z", ".a", ".avi", ".bin", ".bmp", ".bz2", ".class", ".dat", ".db",
        ".dll", ".doc", ".docx", ".dylib", ".egg", ".eot", ".exe", ".flac", ".gif",
        ".gz", ".ico", ".jar", ".jpeg", ".jpg", ".mkv", ".mov", ".mp3", ".mp4",
        ".o", ".ogg", ".otf", ".pdf", ".png", ".ppt", ".pptx", ".pyc", ".pyo",
        ".rar", ".so", ".sqlite", ".sqlite3", ".svg", ".tar", ".tiff", ".ttf", ".wav", ".webm",
        ".webp", ".whl", ".woff", ".woff2", ".xls", ".xlsx", ".xz", ".zip",
    }
)

DEFAULT_REVIEW_IGNORE_GLOBS = (
    "*.pyc",
    "*.pyo",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.webp",
    "*.gif",
    "*.ico",
    "*.lock",
    ".nanobot_snapshot.json",
)

_LOCK_FILENAMES = frozenset(
    {
        "bun.lockb",
        "cargo.lock",
        "composer.lock",
        "flake.lock",
        "gemfile.lock",
        "go.sum",
        "package-lock.json",
        "pipfile.lock",
        "pnpm-lock.yaml",
        "poetry.lock",
        "yarn.lock",
    }
)
_GENERATED_MARKERS = (
    "auto-generated",
    "autogenerated",
    "code generated",
    "do not edit",
    "generated by",
)
_GENERATED_SUFFIXES = (".bundle.js", ".map", ".min.css", ".min.js")


def review_file_filter_reason(rel_path: str, text: str | None = None) -> str | None:
    """Return why a review file should be excluded, or ``None`` when it is usable."""
    normalized = rel_path.strip().replace("\\", "/").lstrip("/")
    if not normalized:
        return "empty_path"
    path = PurePosixPath(normalized)
    parts = tuple(part.lower() for part in path.parts)
    if any(part in DEFAULT_REVIEW_IGNORE_DIRS for part in parts[:-1]):
        return "ignored_directory"
    name = path.name.lower()
    if path.suffix.lower() in DEFAULT_REVIEW_BINARY_EXTS:
        return "binary_file"
    if name in _LOCK_FILENAMES or name.endswith(".lock"):
        return "lock_file"
    if normalized.lower().endswith(_GENERATED_SUFFIXES):
        return "generated_asset"
    if text is not None:
        header = "\n".join(text.splitlines()[:5]).lower()
        if any(marker in header for marker in _GENERATED_MARKERS):
            return "generated_file"
    return None
