from nanoreview.review.file_filter import review_file_filter_reason


def test_review_file_filter_excludes_common_non_source_inputs() -> None:
    assert review_file_filter_reason("node_modules/pkg/index.js") == "ignored_directory"
    assert review_file_filter_reason("package-lock.json") == "lock_file"
    assert review_file_filter_reason("assets/app.min.js") == "generated_asset"
    assert review_file_filter_reason("image.png") == "binary_file"
    assert review_file_filter_reason("src/generated.py", "# generated by tool\nprint('x')") == "generated_file"


def test_review_file_filter_keeps_source_and_configuration() -> None:
    assert review_file_filter_reason("src/auth.py", "def check():\n    return True\n") is None
    assert review_file_filter_reason("pyproject.toml", "[project]\nname = 'nanobot'\n") is None
