"""Chunk quality filtering to reduce embedding token consumption.

Filters out low-value chunks (lock files, imports-only, boilerplate) from
embedding while keeping them in FTS5 for lexical search.
"""

from __future__ import annotations

import re
from pathlib import PurePosixPath

_SKIP_EMBED_FILENAMES = frozenset({
    "package-lock.json", "yarn.lock", "pnpm-lock.yaml", "Pipfile.lock",
    "poetry.lock", "Gemfile.lock", "composer.lock", "Cargo.lock",
    "go.sum", "flake.lock", "bun.lockb",
})

_SKIP_EMBED_SUFFIXES = (".min.js", ".min.css", ".bundle.js", ".map")

_GENERATED_MARKERS = (
    "auto-generated", "autogenerated", "do not edit",
    "code generated", "generated by",
)

_IMPORT_RE = re.compile(
    r"^\s*(import\s|from\s\S+\s+import|require\(|#include|using\s|"
    r"package\s|const\s+\w+\s*=\s*require|export\s*\{)",
)


def should_skip_file_embedding(rel_path: str, text: str) -> bool:
    """Return True if the file's chunks should skip embedding (still indexed by FTS5)."""
    p = PurePosixPath(rel_path)

    if p.name in _SKIP_EMBED_FILENAMES:
        return True

    if any(rel_path.endswith(s) for s in _SKIP_EMBED_SUFFIXES):
        return True

    if p.suffix.lower() == ".json" and len(text) > 50_000:
        return True

    header = "\n".join(text.splitlines()[:5]).lower()
    if any(m in header for m in _GENERATED_MARKERS):
        return True

    lines = text.splitlines()
    if lines:
        avg_len = sum(len(ln) for ln in lines) / len(lines)
        if avg_len > 500:
            return True

    return False


def is_chunk_valid(text: str, kind: str) -> bool:
    """Return True if the chunk is worth embedding."""
    if kind in ("function", "class"):
        return True

    stripped = text.strip()
    if not stripped:
        return False

    lines = [ln for ln in stripped.splitlines() if ln.strip()]
    if len(lines) < 2:
        return False

    content_chars = sum(len(ln.strip()) for ln in lines)
    if content_chars < 30:
        return False

    import_lines = sum(1 for ln in lines if _IMPORT_RE.match(ln))
    if len(lines) > 0 and import_lines / len(lines) > 0.85:
        return False

    return True
